import { DESKTOP_DIRECT_REQUEST_CHANNELS } from './desktop-direct-request'
import { OAuthIpcChannels } from './oauth/types'

/**
 * Every `ipcMain.handle` channel the renderer is allowed to call through
 * `window.electronAPI.invoke`. This is the single source of truth for the
 * preload bridge's channel allowlist (see src/preload/index.ts).
 *
 * Historically the preload bridge forwarded `ipcRenderer.invoke` directly,
 * with no channel restriction at all — any JavaScript that ever ran in the
 * renderer (an XSS payload, a compromised dependency, a malicious MCP
 * server response rendered into the DOM, ...) could invoke *any* handler
 * registered in the main process, including ones never intended for
 * renderer use. Every channel below is one that a real, current renderer
 * call site actually invokes (audited against every `.invoke(...)` call
 * under src/renderer and every `ipcMain.handle(...)` registration under
 * src/main). Anything not listed here is refused.
 *
 * When you add a new IPC channel the renderer needs to call, add it here
 * too — the preload bridge will otherwise reject it at runtime.
 */
export const ALLOWED_INVOKE_CHANNELS: ReadonlySet<string> = new Set<string>([
  'agent-persona:scan-local-memories',
  'analysticTrackingEvent',
  'appLog',
  'clearLogs',
  'delStoreBlob',
  'delStoreValue',
  'dialog:openDirectory',
  'ensureAutoLaunch',
  'ensureProxy',
  'ensureShortcutConfig',
  'exportLogs',
  'fs:edit',
  'fs:list',
  'fs:read',
  'fs:read-image',
  'fs:search',
  'fs:write',
  'getAllStoreKeys',
  'getAllStoreValues',
  'getArch',
  'getConfig',
  'getDeviceName',
  'getLocale',
  'getPlatform',
  'getSettings',
  'getStoreBlob',
  'getStoreValue',
  'getVersion',
  'install-update',
  'isFullscreen',
  'kb:create',
  'kb:delete',
  'kb:file:count',
  'kb:file:delete',
  'kb:file:get-metas',
  'kb:file:list',
  'kb:file:list-paginated',
  'kb:file:pause',
  'kb:file:read-chunks',
  'kb:file:resume',
  'kb:file:retry',
  'kb:file:upload',
  'kb:list',
  'kb:search',
  'kb:update',
  'listStoreBlobKeys',
  'mcp:stdio-transport:close',
  'mcp:stdio-transport:create',
  'mcp:stdio-transport:send',
  'mcp:stdio-transport:start',
  'openLink',
  'parseFileLocally',
  'parseUrl',
  'parser:cancel-mineru-parse',
  'parser:parse-file-with-mineru',
  'parser:test-mineru',
  'relaunch',
  'sandbox:check-availability',
  'sandbox:copy-blob',
  'sandbox:copy-file',
  'sandbox:create-html-preview',
  'sandbox:edit',
  'sandbox:exec-code',
  'sandbox:export-file',
  'sandbox:find',
  'sandbox:has-artifacts',
  'sandbox:init-temp',
  'sandbox:kill',
  'sandbox:ls',
  'sandbox:persist-artifact',
  'sandbox:read',
  'sandbox:read-file-base64',
  'sandbox:read-file-bytes',
  'sandbox:remove-artifacts',
  'sandbox:reset',
  'sandbox:resolve-working-dir',
  'sandbox:run-command',
  'sandbox:search',
  'sandbox:seed-blobs',
  'sandbox:status',
  'sandbox:write',
  'session-attachment-rag:cleanup-orphans',
  'session-attachment-rag:clear-all',
  'session-attachment-rag:create',
  'session-attachment-rag:delete-attachment',
  'session-attachment-rag:delete-message-attachments',
  'session-attachment-rag:delete-session-attachments',
  'session-attachment-rag:get-attachments',
  'session-attachment-rag:get-debug-snapshot',
  'session-attachment-rag:query',
  'session-attachment-rag:read-parents',
  'session-attachment-rag:rebind',
  'session-attachment-rag:retry',
  'session-attachment-rag:run-maintenance',
  'setAllStoreValues',
  'setFullscreen',
  'setStoreBlob',
  'setStoreValue',
  'shouldShowAboutDialogWhenStartUp',
  'shouldUseDarkColors',
  'skills:check-update',
  'skills:check-updates-batch',
  'skills:delete',
  'skills:discover',
  'skills:execute-script',
  'skills:get-directory',
  'skills:install',
  'skills:install-from-sandbox',
  'skills:install-marketplace',
  'skills:load',
  'skills:open-directory',
  'skills:resolve-command-retry',
  'skills:resolve-user-exec-cwd',
  'skills:scan-repo',
  'skills:sync-builtin',
  'skills:user-exec',
  'skills:user-exec-cancel',
  'switch-theme',
  'updater:check',
  'window:close',
  'window:is-focused',
  'window:is-maximized',
  'window:maximize',
  'window:minimize',
  'window:unmaximize',
  'workspace:read-instructions',
  // Pulled from the shared constant objects so those stay the single
  // source of truth for their own channel strings.
  ...Object.values(OAuthIpcChannels),
  ...Object.values(DESKTOP_DIRECT_REQUEST_CHANNELS),
])
